    
version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    
  admin-mongo:
    image: 0x59/admin-mongo:latest
    ports:
        - 8082:8082
    environment:
        - PORT=8082
        - CONN_NAME=mongo
        - DB_HOST=mongo
    
  lancamento.api:
    environment:
        - ASPNETCORE_ENVIRONMENT=local
    expose:
      - "80"
    ports:
      - 5101:80
    build: 
        context: .
        dockerfile: Dockerfile
        args:
            projeto: Lancamento
            pathProjeto: Lancamento
            repositorio: https://github.com/brunotanaka/Lancamento.git